version: '3.8'
services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5000:5000"
    networks:
      - backend
    volumes:
      - ./gerenciamento:/app

  reservas:
    build: ./reservas
    container_name: reservas
    ports:
      - "5001:5000"
    depends_on:
      - gerenciamento
    networks:
      - backend
    volumes:
      - ./reservas:/app
    environment:
      - GERENCIAMENTO_URL=http://gerenciamento:5000

  atividades:
    build: ./atividades
    container_name: atividades
    ports:
      - "5002:5000"
    depends_on:
      - gerenciamento
    networks:
      - backend
    volumes:
      - ./atividades:/app
    environment:
      - GERENCIAMENTO_URL=http://gerenciamento:5000

networks:
  backend:
    driver: bridge
